CREATE TABLE tb_users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(15) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    encoded_password VARCHAR(255),
    auth_provider    VARCHAR(32) NOT NULL DEFAULT 'local',
    roles            VARCHAR(255) ARRAY,
    deleted     BOOLEAN DEFAULT false,

    CONSTRAINT tb_users_email_UK    UNIQUE(email),
    CONSTRAINT tb_users_username_UK UNIQUE(username)
);

CREATE TABLE tb_categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(64) NOT NULL,
    color VARCHAR(16),

    CONSTRAINT tb_categories_UK UNIQUE(name)
);

CREATE TABLE tb_workflow_status (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT tb_workflow_status_UK UNIQUE (name)
);

CREATE TABLE tb_workflows (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255),
    start_id       BIGINT NOT NULL,
    phase_start_id BIGINT,

    CONSTRAINT tb_workflows_UK UNIQUE (name),
    CONSTRAINT tb_workflows_start_FK FOREIGN KEY (start_id) REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflows_phase_start_FK FOREIGN KEY (phase_start_id) REFERENCES tb_workflow_status
);

CREATE TABLE tb_projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,
    description TEXT,
    prefix      VARCHAR(15) NOT NULL,
    workflow_id BIGINT NOT NULL,
    owner_id    BIGINT NOT NULL,
    security_level VARCHAR(16) NOT NULL DEFAULT 'INTERNAL',
    ticket_template_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ticket_template_title VARCHAR(255),
    ticket_template_description TEXT,
    ticket_template_category_id BIGINT REFERENCES tb_categories,
    ticket_template_priority VARCHAR(16),
    phase_template_objective TEXT,

    CONSTRAINT tb_project_UK UNIQUE (name),
    CONSTRAINT tb_project_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows,
    CONSTRAINT tb_project_owner_FK FOREIGN KEY (owner_id) REFERENCES tb_users,
    CONSTRAINT tb_projects_security_level_CK CHECK (security_level IN ('PRIVATE', 'INTERNAL', 'PUBLIC'))
);

CREATE TABLE tb_project_members (
    project_id BIGINT NOT NULL REFERENCES tb_projects,
    user_id    BIGINT NOT NULL REFERENCES tb_users,
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE tb_project_phase_deliverable_templates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES tb_projects,
    sort_order INT NOT NULL DEFAULT 0,
    text       TEXT NOT NULL
);

CREATE TABLE tb_versions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES tb_projects,
    label       VARCHAR(64) NOT NULL,
    description TEXT,

    CONSTRAINT tb_versions_project_label_UK UNIQUE (project_id, label)
);

CREATE TABLE tb_phases (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id             BIGINT NOT NULL REFERENCES tb_projects,
    name                   VARCHAR(128) NOT NULL,
    objective              TEXT,
    status                 VARCHAR(16) NOT NULL,
    start_date             DATE,
    end_date               DATE,
    deliverable_version_id BIGINT REFERENCES tb_versions,
    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at           TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE tb_phase_deliverables (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id   BIGINT NOT NULL REFERENCES tb_phases,
    sort_order INT NOT NULL DEFAULT 0,
    text       TEXT NOT NULL
);

CREATE TABLE tb_tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier  VARCHAR(25) NOT NULL,
    title       VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    assignee_id BIGINT,
    author_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,
    priority    VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    ticket_type VARCHAR(16) NOT NULL DEFAULT 'TASK',
    backlog_rank INT NOT NULL DEFAULT 0,
    deleted     BOOLEAN DEFAULT false,
    finished_at TIMESTAMP(6) WITH TIME ZONE,
    canceled_at TIMESTAMP(6) WITH TIME ZONE,
    story_points INTEGER CHECK (story_points IS NULL OR story_points >= 0),
    due_date    DATE,
    observed_version_id BIGINT REFERENCES tb_versions,
    target_version_id   BIGINT REFERENCES tb_versions,
    phase_id            BIGINT REFERENCES tb_phases,
    search_vector       tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(identifier, '') || ' ' || coalesce(title, '') || ' ' || coalesce(description, ''))
    ) STORED,

    CONSTRAINT tb_project_ID_UK       UNIQUE (identifier),
    CONSTRAINT tb_tickets_ticket_type_CK CHECK (ticket_type IN ('EPIC', 'STORY', 'TASK')),
    CONSTRAINT tb_tickets_assignee_FK FOREIGN KEY (assignee_id) REFERENCES tb_users,
    CONSTRAINT tb_tickets_author_FK   FOREIGN KEY (author_id)   REFERENCES tb_users,
    CONSTRAINT tb_tickets_category_FK FOREIGN KEY (category_id) REFERENCES tb_categories,
    CONSTRAINT tb_tickets_project_FK  FOREIGN KEY (project_id)  REFERENCES tb_projects,
    CONSTRAINT tb_tickets_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status
);

CREATE INDEX idx_tickets_search_vector ON tb_tickets USING GIN (search_vector);
CREATE INDEX idx_tickets_project_backlog_rank
    ON tb_tickets (project_id, backlog_rank)
    WHERE deleted = false;

CREATE TABLE tb_tickets_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL,
    subscriber_id   BIGINT NOT NULL,

    CONSTRAINT tb_tickets_subscribers_ticket_FK     FOREIGN KEY (ticket_id)     REFERENCES tb_tickets,
    CONSTRAINT tb_tickets_subscribers_subscriber_FK FOREIGN KEY (subscriber_id) REFERENCES tb_users
);

CREATE TABLE tb_ticket_links (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ticket_id BIGINT NOT NULL REFERENCES tb_tickets,
    target_ticket_id BIGINT NOT NULL REFERENCES tb_tickets,
    link_type        VARCHAR(32) NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by       BIGINT NOT NULL REFERENCES tb_users,
    CONSTRAINT uk_ticket_link UNIQUE (source_ticket_id, target_ticket_id, link_type),
    CONSTRAINT ck_ticket_link_not_self CHECK (source_ticket_id <> target_ticket_id)
);
CREATE INDEX idx_ticket_links_source ON tb_ticket_links (source_ticket_id);
CREATE INDEX idx_ticket_links_target ON tb_ticket_links (target_ticket_id);

CREATE TABLE tb_project_git_repositories (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       BIGINT NOT NULL,
    remote_url       VARCHAR(512) NOT NULL,
    provider         VARCHAR(32),
    default_branch   VARCHAR(128),
    webhook_secret   VARCHAR(128),
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_project_git_repositories_project_FK FOREIGN KEY (project_id) REFERENCES tb_projects,
    CONSTRAINT tb_project_git_repositories_project_UK UNIQUE (project_id)
);

CREATE TABLE tb_ticket_commits (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL,
    project_id      BIGINT NOT NULL,
    sha             VARCHAR(64) NOT NULL,
    message         TEXT NOT NULL,
    author_name     VARCHAR(255),
    author_email    VARCHAR(255),
    matched_user_id BIGINT,
    committed_at    TIMESTAMP(6) WITH TIME ZONE,
    commit_url      VARCHAR(1024),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_ticket_commits_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets,
    CONSTRAINT tb_ticket_commits_project_FK FOREIGN KEY (project_id) REFERENCES tb_projects,
    CONSTRAINT tb_ticket_commits_user_FK FOREIGN KEY (matched_user_id) REFERENCES tb_users,
    CONSTRAINT tb_ticket_commits_ticket_sha_UK UNIQUE (ticket_id, sha)
);

CREATE INDEX idx_ticket_commits_ticket ON tb_ticket_commits (ticket_id);
CREATE INDEX idx_ticket_commits_project ON tb_ticket_commits (project_id);

CREATE TABLE tb_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    author_id  BIGINT,
    ticket_id  BIGINT NOT NULL,
    via_agent  BOOLEAN NOT NULL DEFAULT FALSE,
    search_vector tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(content, ''))
    ) STORED,

    CONSTRAINT tb_comment_user_FK   FOREIGN KEY (author_id) REFERENCES tb_users,
    CONSTRAINT tb_comment_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets
);

CREATE INDEX idx_comments_search_vector ON tb_comments USING GIN (search_vector);

CREATE TABLE tb_ticket_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    action       VARCHAR(32)  NOT NULL,
    field        VARCHAR(64),
    old_value    TEXT,
    new_value    TEXT,
    reference_id BIGINT,
    timestamp    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ticket_id    BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    via_agent    BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT tb_ticket_history_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets,
    CONSTRAINT tb_ticket_history_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users
);

CREATE TABLE tb_workflow_statuses (
    workflow_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,

    CONSTRAINT tb_workflow_statuses_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_statuses_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_workflow_transitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id     BIGINT NOT NULL,
    to_id       BIGINT NOT NULL,
    workflow_id BIGINT,

    CONSTRAINT tb_workflow_transition_UK  UNIQUE (workflow_id, from_id, to_id),
    CONSTRAINT tb_workflow_transition_from_FK     FOREIGN KEY (from_id)     REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_to_FK       FOREIGN KEY (to_id)       REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_workflow_finish_statuses (
    workflow_id BIGINT NOT NULL REFERENCES tb_workflows,
    status_id   BIGINT NOT NULL REFERENCES tb_workflow_status,
    outcome     VARCHAR(16) NOT NULL,

    PRIMARY KEY (workflow_id, status_id)
);

CREATE TABLE tb_workflow_wip_limits (
    workflow_id BIGINT NOT NULL REFERENCES tb_workflows,
    status_id   BIGINT NOT NULL REFERENCES tb_workflow_status,
    wip_limit   INTEGER NOT NULL CHECK (wip_limit >= 1),

    PRIMARY KEY (workflow_id, status_id)
);

CREATE TABLE tb_notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(56) NOT NULL,
    receive_id  BIGINT NOT NULL,
    reffer_id   BIGINT NOT NULL,
    read        BOOLEAN DEFAULT false,
    content     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_notifications_receive_FK FOREIGN KEY (receive_id) REFERENCES tb_users,
    CONSTRAINT tb_notifications_reffer_FK  FOREIGN KEY (reffer_id)  REFERENCES tb_tickets
);

CREATE INDEX idx_notifications_receive_created ON tb_notifications (receive_id, created_at DESC, id DESC);

CREATE TABLE tb_password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP(6) NOT NULL,
    token       VARCHAR(255) NOT NULL, -- SHA-256 hex of opaque reset token
    password    VARCHAR(8) NOT NULL,
    used        BOOLEAN NOT NULL,
    user_id     BIGINT NOT NULL,

    CONSTRAINT tb_password_reset_tokens_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users,
    CONSTRAINT tb_password_reset_tokens_token_UK UNIQUE(token)
);

CREATE TABLE tb_refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL, -- SHA-256 hex of opaque refresh token
    expires_at  TIMESTAMP(6) NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    user_id     BIGINT NOT NULL,

    CONSTRAINT tb_refresh_tokens_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users,
    CONSTRAINT tb_refresh_tokens_token_UK UNIQUE(token)
);

CREATE TABLE tb_api_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    name         VARCHAR(255) NOT NULL,
    token_hash   VARCHAR(64) NOT NULL,
    token_prefix VARCHAR(32) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP(6) WITH TIME ZONE,
    revoked_at   TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_api_tokens_user_FK FOREIGN KEY (user_id) REFERENCES tb_users,
    CONSTRAINT tb_api_tokens_hash_UK UNIQUE (token_hash)
);

CREATE INDEX idx_api_tokens_user ON tb_api_tokens (user_id);

CREATE TABLE tb_service_accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_service_accounts_project_FK FOREIGN KEY (project_id) REFERENCES tb_projects,
    CONSTRAINT tb_service_accounts_user_FK    FOREIGN KEY (user_id)    REFERENCES tb_users,
    CONSTRAINT tb_service_accounts_user_UK    UNIQUE (user_id)
);

CREATE INDEX idx_service_accounts_project ON tb_service_accounts (project_id);

CREATE TABLE tb_service_account_tokens (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_account_id BIGINT NOT NULL,
    name               VARCHAR(255) NOT NULL,
    token_hash         VARCHAR(64) NOT NULL,
    token_prefix       VARCHAR(32) NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_used_at       TIMESTAMP(6) WITH TIME ZONE,
    revoked_at         TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_service_account_tokens_sa_FK FOREIGN KEY (service_account_id) REFERENCES tb_service_accounts,
    CONSTRAINT tb_service_account_tokens_hash_UK UNIQUE (token_hash)
);

CREATE INDEX idx_service_account_tokens_sa ON tb_service_account_tokens (service_account_id);

CREATE TABLE tb_ticket_imports (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT,
    author_id             BIGINT NOT NULL,
    file_name             VARCHAR(255) NOT NULL,
    headers_json          TEXT NOT NULL,
    title_column          VARCHAR(255),
    description_column    VARCHAR(255),
    category_column       VARCHAR(255),
    project_column        VARCHAR(255),
    priority_column       VARCHAR(255),
    story_points_column   VARCHAR(255),
    assignee_email_column VARCHAR(255),
    status_column         VARCHAR(255),
    custom_field_column_mapping TEXT,
    status                VARCHAR(32) NOT NULL,
    row_count             INT NOT NULL,
    truncated             BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_ticket_imports_project_FK FOREIGN KEY (project_id) REFERENCES tb_projects,
    CONSTRAINT tb_ticket_imports_author_FK  FOREIGN KEY (author_id)  REFERENCES tb_users
);

CREATE TABLE tb_ticket_import_rows (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id           BIGINT NOT NULL,
    row_number          INT NOT NULL,
    raw_values_json     TEXT NOT NULL,
    title               VARCHAR(255),
    description         TEXT,
    category_name       VARCHAR(64),
    project_name        VARCHAR(64),
    priority            VARCHAR(16),
    story_points        INTEGER,
    assignee_email      VARCHAR(255),
    status_name         VARCHAR(255),
    valid               BOOLEAN,
    validation_errors_json TEXT,
    custom_field_values_json TEXT,
    ticket_id           BIGINT,
    import_error        TEXT,

    CONSTRAINT tb_ticket_import_rows_import_FK FOREIGN KEY (import_id) REFERENCES tb_ticket_imports,
    CONSTRAINT tb_ticket_import_rows_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets
);


CREATE TABLE tb_saved_queries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(36)  NOT NULL UNIQUE,
    name         VARCHAR(255) NOT NULL,
    query_text   TEXT         NOT NULL,
    show_at_home BOOLEAN      NOT NULL DEFAULT FALSE,
    owner_id     BIGINT       NOT NULL REFERENCES tb_users,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_saved_queries_owner ON tb_saved_queries(owner_id);

CREATE TABLE tb_dashboard_layouts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES tb_users,
    project_id BIGINT NOT NULL REFERENCES tb_projects,
    widgets    TEXT NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT tb_dashboard_layouts_user_project_UK UNIQUE (user_id, project_id)
);

CREATE INDEX idx_dashboard_layouts_user_project ON tb_dashboard_layouts(user_id, project_id);

CREATE TABLE tb_custom_fields (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_key         VARCHAR(32)  NOT NULL,
    label             VARCHAR(128) NOT NULL,
    field_type        VARCHAR(16)  NOT NULL,
    required          BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    project_id        BIGINT,
    workflow_id       BIGINT,
    string_max_length INT,
    integer_min       INT,
    integer_max       INT,
    sort_order        INT          NOT NULL DEFAULT 0,

    CONSTRAINT tb_custom_fields_project_FK  FOREIGN KEY (project_id)  REFERENCES tb_projects,
    CONSTRAINT tb_custom_fields_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows,
    CONSTRAINT tb_custom_fields_owner_CHK CHECK (
        (project_id IS NOT NULL AND workflow_id IS NULL)
        OR (project_id IS NULL AND workflow_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_custom_fields_project_key ON tb_custom_fields (project_id, field_key)
    WHERE project_id IS NOT NULL;
CREATE UNIQUE INDEX uk_custom_fields_workflow_key ON tb_custom_fields (workflow_id, field_key)
    WHERE workflow_id IS NOT NULL;
CREATE INDEX idx_custom_fields_project ON tb_custom_fields (project_id);
CREATE INDEX idx_custom_fields_workflow ON tb_custom_fields (workflow_id);

CREATE TABLE tb_custom_field_enum_options (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_field_id BIGINT       NOT NULL REFERENCES tb_custom_fields ON DELETE CASCADE,
    option_value    VARCHAR(128) NOT NULL,
    label           VARCHAR(128) NOT NULL,
    sort_order      INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_custom_field_enum_option UNIQUE (custom_field_id, option_value)
);

CREATE TABLE tb_custom_field_status_required (
    custom_field_id BIGINT NOT NULL REFERENCES tb_custom_fields ON DELETE CASCADE,
    status_id       BIGINT NOT NULL REFERENCES tb_workflow_status,
    PRIMARY KEY (custom_field_id, status_id)
);

CREATE TABLE tb_ticket_custom_field_values (
    ticket_id       BIGINT NOT NULL REFERENCES tb_tickets ON DELETE CASCADE,
    custom_field_id BIGINT NOT NULL REFERENCES tb_custom_fields,
    string_value    VARCHAR(255),
    text_value      TEXT,
    integer_value   INT,
    boolean_value   BOOLEAN,
    enum_option_id  BIGINT REFERENCES tb_custom_field_enum_options,
    PRIMARY KEY (ticket_id, custom_field_id)
);

CREATE INDEX idx_ticket_cf_values_field ON tb_ticket_custom_field_values (custom_field_id);

CREATE TABLE tb_project_ticket_template_custom_values (
    project_id      BIGINT NOT NULL REFERENCES tb_projects ON DELETE CASCADE,
    custom_field_id BIGINT NOT NULL REFERENCES tb_custom_fields ON DELETE CASCADE,
    string_value    VARCHAR(255),
    text_value      TEXT,
    integer_value   INT,
    boolean_value   BOOLEAN,
    enum_option_id  BIGINT REFERENCES tb_custom_field_enum_options,
    PRIMARY KEY (project_id, custom_field_id)
);

-- Usuário com apenas a role ADMIN
INSERT INTO tb_users (username, name, email, encoded_password, roles) VALUES ('admin', 'System Administrator', 'sysadmin@issues.ui', 'IwS3Mm4oGEfpwPDC3Vom20ViYgXhVCxHeBGr8aluY9tC9o668ghxJ2fMQQUwq+7GWJkzX1HguXOtdwVkblUzTw==', '{ADMIN}');