CREATE TABLE tb_users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(15) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    encoded_password VARCHAR(255) NOT NULL,
    roles            VARCHAR(255) ARRAY,
    deleted     BOOLEAN DEFAULT false,

    CONSTRAINT tb_users_email_UK    UNIQUE(email),
    CONSTRAINT tb_users_username_UK UNIQUE(username)
);

CREATE TABLE tb_categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(64) NOT NULL,
    color VARCHAR(16),

    CONSTRAINT tb_categories_UK UNIQUE(name)
);

CREATE TABLE tb_workflow_status (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT tb_workflow_status_UK UNIQUE (name)
);

CREATE TABLE tb_workflows (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255),
    start_id       BIGINT NOT NULL,
    phase_start_id BIGINT,

    CONSTRAINT tb_workflows_UK UNIQUE (name),
    CONSTRAINT tb_workflows_start_FK FOREIGN KEY (start_id) REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflows_phase_start_FK FOREIGN KEY (phase_start_id) REFERENCES tb_workflow_status
);

CREATE TABLE tb_projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,
    description TEXT,
    prefix      VARCHAR(15) NOT NULL,
    workflow_id BIGINT NOT NULL,
    owner_id    BIGINT NOT NULL,
    ticket_template_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ticket_template_title VARCHAR(255),
    ticket_template_description TEXT,
    ticket_template_category_id BIGINT REFERENCES tb_categories,
    ticket_template_priority VARCHAR(16),
    phase_template_objective TEXT,

    CONSTRAINT tb_project_UK UNIQUE (name),
    CONSTRAINT tb_project_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows,
    CONSTRAINT tb_project_owner_FK FOREIGN KEY (owner_id) REFERENCES tb_users
);

CREATE TABLE tb_project_members (
    project_id BIGINT NOT NULL REFERENCES tb_projects,
    user_id    BIGINT NOT NULL REFERENCES tb_users,
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE tb_project_phase_deliverable_templates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES tb_projects,
    sort_order INT NOT NULL DEFAULT 0,
    text       TEXT NOT NULL
);

CREATE TABLE tb_versions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES tb_projects,
    label       VARCHAR(64) NOT NULL,
    description TEXT,

    CONSTRAINT tb_versions_project_label_UK UNIQUE (project_id, label)
);

CREATE TABLE tb_phases (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id             BIGINT NOT NULL REFERENCES tb_projects,
    name                   VARCHAR(128) NOT NULL,
    objective              TEXT,
    status                 VARCHAR(16) NOT NULL,
    start_date             DATE,
    end_date               DATE,
    deliverable_version_id BIGINT REFERENCES tb_versions,
    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at           TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE tb_phase_deliverables (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id   BIGINT NOT NULL REFERENCES tb_phases,
    sort_order INT NOT NULL DEFAULT 0,
    text       TEXT NOT NULL
);

CREATE TABLE tb_tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier  VARCHAR(25) NOT NULL,
    title       VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    assignee_id BIGINT,
    author_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,
    priority    VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    deleted     BOOLEAN DEFAULT false,
    finished_at TIMESTAMP(6) WITH TIME ZONE,
    observed_version_id BIGINT REFERENCES tb_versions,
    target_version_id   BIGINT REFERENCES tb_versions,
    phase_id            BIGINT REFERENCES tb_phases,

    CONSTRAINT tb_project_ID_UK       UNIQUE (identifier),
    CONSTRAINT tb_tickets_assignee_FK FOREIGN KEY (assignee_id) REFERENCES tb_users,
    CONSTRAINT tb_tickets_author_FK   FOREIGN KEY (author_id)   REFERENCES tb_users,
    CONSTRAINT tb_tickets_category_FK FOREIGN KEY (category_id) REFERENCES tb_categories,
    CONSTRAINT tb_tickets_project_FK  FOREIGN KEY (project_id)  REFERENCES tb_projects,
    CONSTRAINT tb_tickets_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status
);

CREATE TABLE tb_tickets_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL,
    subscriber_id   BIGINT NOT NULL,

    CONSTRAINT tb_tickets_subscribers_ticket_FK     FOREIGN KEY (ticket_id)     REFERENCES tb_tickets,
    CONSTRAINT tb_tickets_subscribers_subscriber_FK FOREIGN KEY (subscriber_id) REFERENCES tb_users
);

CREATE TABLE tb_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    author_id  BIGINT,
    ticket_id  BIGINT NOT NULL,

    CONSTRAINT tb_comment_user_FK   FOREIGN KEY (author_id) REFERENCES tb_users,
    CONSTRAINT tb_comment_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets
);

CREATE TABLE tb_ticket_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    action       VARCHAR(32)  NOT NULL,
    field        VARCHAR(32),
    old_value    TEXT,
    new_value    TEXT,
    reference_id BIGINT,
    timestamp    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ticket_id    BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,

    CONSTRAINT tb_ticket_history_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets,
    CONSTRAINT tb_ticket_history_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users
);

CREATE TABLE tb_workflow_statuses (
    workflow_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,

    CONSTRAINT tb_workflow_statuses_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_statuses_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_workflow_transitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id     BIGINT NOT NULL,
    to_id       BIGINT NOT NULL,
    workflow_id BIGINT,

    CONSTRAINT tb_workflow_transition_UK  UNIQUE (workflow_id, from_id, to_id),
    CONSTRAINT tb_workflow_transition_from_FK     FOREIGN KEY (from_id)     REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_to_FK       FOREIGN KEY (to_id)       REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_workflow_finish_statuses (
    workflow_id BIGINT NOT NULL REFERENCES tb_workflows,
    status_id   BIGINT NOT NULL REFERENCES tb_workflow_status,
    outcome     VARCHAR(16) NOT NULL,

    PRIMARY KEY (workflow_id, status_id)
);

CREATE TABLE tb_notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(56) NOT NULL,
    receive_id  BIGINT NOT NULL,
    reffer_id   BIGINT NOT NULL,
    read        BOOLEAN DEFAULT false,
    content     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_notifications_receive_FK FOREIGN KEY (receive_id) REFERENCES tb_users,
    CONSTRAINT tb_notifications_reffer_FK  FOREIGN KEY (reffer_id)  REFERENCES tb_tickets
);

CREATE TABLE tb_password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP(6) NOT NULL,
    token       VARCHAR(255) NOT NULL,
    password    VARCHAR(8) NOT NULL,
    used        BOOLEAN NOT NULL,
    user_id     BIGINT NOT NULL,

    CONSTRAINT tb_password_reset_tokens_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users,
    CONSTRAINT tb_password_reset_tokens_token_UK UNIQUE(token)
);

CREATE TABLE tb_ticket_imports (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT,
    author_id             BIGINT NOT NULL,
    file_name             VARCHAR(255) NOT NULL,
    headers_json          TEXT NOT NULL,
    title_column          VARCHAR(255),
    description_column    VARCHAR(255),
    category_column       VARCHAR(255),
    project_column        VARCHAR(255),
    priority_column       VARCHAR(255),
    assignee_email_column VARCHAR(255),
    status_column         VARCHAR(255),
    status                VARCHAR(32) NOT NULL,
    row_count             INT NOT NULL,
    truncated             BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT tb_ticket_imports_project_FK FOREIGN KEY (project_id) REFERENCES tb_projects,
    CONSTRAINT tb_ticket_imports_author_FK  FOREIGN KEY (author_id)  REFERENCES tb_users
);

CREATE TABLE tb_ticket_import_rows (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id           BIGINT NOT NULL,
    row_number          INT NOT NULL,
    raw_values_json     TEXT NOT NULL,
    title               VARCHAR(255),
    description         TEXT,
    category_name       VARCHAR(64),
    project_name        VARCHAR(64),
    priority            VARCHAR(16),
    assignee_email      VARCHAR(255),
    status_name         VARCHAR(255),
    valid               BOOLEAN,
    validation_errors_json TEXT,
    ticket_id           BIGINT,
    import_error        TEXT,

    CONSTRAINT tb_ticket_import_rows_import_FK FOREIGN KEY (import_id) REFERENCES tb_ticket_imports,
    CONSTRAINT tb_ticket_import_rows_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets
);


-- Usuário com apenas a role ADMIN
INSERT INTO tb_users (username, name, email, encoded_password, roles) VALUES ('admin', 'System Administrator', 'sysadmin@issues.ui', 'IwS3Mm4oGEfpwPDC3Vom20ViYgXhVCxHeBGr8aluY9tC9o668ghxJ2fMQQUwq+7GWJkzX1HguXOtdwVkblUzTw==', '{ADMIN}');